### ISSUE TITLE
Absence of ordered set in the library 

### ISSUE THREAD

**Issue by Zenohate** [jtomschroeder/crystalline#15]
I am in need of an Ordered Set and am planning to implement one from this library implementation of Red Black tree.

As such to avoid code duplication, I will reimplement the RB Tree Map as an RB Set of pairs. What do you think of it?

**Comment by jtomschroeder** [comment]
Is it possible to wrap the rb-tree map and ignore the *value* (e.g. treat as unit or nil)? This is how Rust handles it.

**Comment by Zenohate** [comment]
I guess it is possible, but it makes the whole a lot less efficient in terms of memory, and hence slow things down, while the reverse approach does neither of those (it is the way it is defined in C++ for example).
I remind you that a Nil will take at least the class of it as extra memory.

**Comment by jtomschroeder** [comment]
Yeah, without zero-sized structures, you're right that it would be less memory-efficient. 

I really like the idea of adding an ordered set to `crystalline`. Please send a PR with your alternative implementation and we can have a deeper look!
