### ISSUE TITLE
Strange benchmarks.

### ISSUE THREAD

**Issue by yxhuvud** [jtomschroeder/crystalline#7]
So I tried to benchmark the priority queue against my own queue with the following code to benchmark the code in this repo, and I find the results I get pretty strange. 
```crystal
require "benchmark"

require "./priority_queue"

values = 100_000.times.map { rand(100_000_000) }.to_a

Benchmark.bm do |x|
  queue = PriorityQueue(Int32).new
  x.report("crystalline - push") {
    values.each do |v|
      queue.push(v, v)
    end
  }
  x.report("crystalline - pop") {
    values.size.times do |v|
      queue.pop
    end
  }
  puts queue.size

  queue2 = PriorityQueue(Int32).new
  x.report("crystalline - mixed") {
    values.each_with_index do |v, i|
      queue2.push(v, v)
      if i % 4 == 0
        queue2.pop
      end
    end
  }
  puts queue2.size

end
```

This outputs 

```
linus@donk:~/prog/pairing_heap$ crystal run src/benchmark.cr --release --no-debug
0
0
                          user     system      total        real
crystalline - push    55.120000   1.290000   56.410000 (  36.032381)
crystalline - pop     0.440000   0.000000   0.440000 (  0.261351)
crystalline - mixed   0.120000   0.000000   0.120000 (  0.069474)

```

The disconnect between `push` and `mixed` is pretty staggering.

For the record, my queue is at https://github.com/yxhuvud/pairing_heap/blob/master/src/priority_queue.cr . It is faster but has slightly different semantics(it picks the least number for starters) and other method names, but it could be interesting to compare against.

**Comment by jtomschroeder** [comment]
@yxhuvud thanks for the analysis. I did some poking around and found some unneeded code that eating cycles. Can you take a look and verify better performance?

**Comment by yxhuvud** [comment]
Yes, the performance is much better now. 

crystalline - push    0.030000   0.000000   0.030000 (  0.022083)
crystalline - pop     0.350000   0.000000   0.350000 (  0.237548)
crystalline - mixed   0.050000   0.000000   0.050000 (  0.043344)

Which makes a lot more sense. Still worse than the values I get of my priority queue, but that makes sense as that particular heap type I use is optimized to the needs of simple priority queues:

mine - insert         0.010000   0.000000   0.010000 (  0.006840)
mine - delete         0.010000   0.000000   0.010000 (  0.019307)
mine - mixed          0.010000   0.000000   0.010000 (  0.005895)

**Comment by jtomschroeder** [comment]
Cool. I'm closing this as the strange behavior seems to be under control. 

@yxhuvud, feel free to submit a PR with improvements to the priority-queue/heap implementation. Also, it might be cool to experiment with making the priority queue generic over an abstract heap (e.g. using the built-in PQ by default, but could use a `pairing-heap` instead).
